name: .NET 5.0

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - '*'

jobs:
  buildAndTest:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
        dotnet: [5.0.202]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and run tests
      run: dotnet fake build -t Test
    - name: Run FSharpLint on itself
      run: dotnet fake build -t SelfCheck

  publish:
    needs: buildAndTest

    strategy:
      matrix:
        os: [windows-latest]
        dotnet: [5.0.202]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      run: dotnet fake build
    - name: Pack
      run: dotnet fake build -t Pack
    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v1.1.0
      with:
        version: ${{ github.ref }}
        path: ./CHANGELOG.md
    - name: Upload binaries to nuget (if nugetKey present)
      env:
        nuget-key: ${{ secrets.NUGET_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'push' && env.nuget-key != null
      run: dotnet fake build -t Push
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.changelog_reader.outputs.log_entry }}
        draft: false
        prerelease: false
    - name: Upload binaries to release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/*.nupkg
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
